### ISSUE TITLE
Ошибка в Calculator.php

### ISSUE THREAD

**Issue by Dekart-hub** [ramz090/PHP_lab#2]
https://github.com/ramz090/PHP_lab/blob/74d0660a6c9d1f50f606b02767e05885f5a557ed/lw1/Calculator.php#L32

- [x] Опечатка в переменной calculatedAmount

**Comment by KernelMrex** [comment]
https://github.com/ramz090/PHP_lab/blob/74d0660a6c9d1f50f606b02767e05885f5a557ed/lw1/Calculator.php#L29-L38

Было бы круто единую точку выхода и использование тернарных операторов

Например:
```php
public function division(float $divider): Calculator
{
    $this->calculatedAmount = ($divider !== 0) ? $this->calculatedAmount / $divider : 0;
    return $this;
}
```
